# Generated by Django 5.1 on 2025-07-30 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_score_level_alter_score_skill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelTwoOJTDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('day_number', models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelTwoOJT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traineeId', models.CharField(max_length=100)),
                ('trainee_name', models.CharField(max_length=100)),
                ('trainer_name', models.CharField(max_length=100)),
                ('revision_date', models.DateField(blank=True, null=True)),
                ('DOJ', models.DateField(blank=True, null=True)),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to='app1.leveltwosection')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainees', to='app1.leveltwotopic')),
            ],
        ),
        migrations.CreateModel(
            name='LevelTwoOJTScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('production_plan', models.IntegerField()),
                ('production_actual', models.IntegerField()),
                ('production_marks', models.IntegerField()),
                ('quality_no_of_rejection', models.IntegerField()),
                ('quality_marks', models.IntegerField()),
                ('Engineer_judge', models.CharField(max_length=100)),
                ('prepared_by', models.CharField(max_length=100)),
                ('approved_by', models.CharField(max_length=100)),
                ('total_production_marks', models.IntegerField(default=0)),
                ('total_quality_marks', models.IntegerField(default=0)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.leveltwoojtdays')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ojtscores', to='app1.leveltwoojt')),
            ],
        ),
    ]
