# Generated by Django 5.1 on 2025-07-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_leveltwoojtdays_leveltwoojt_leveltwoojtscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leveltwodepartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
