# Generated by Django 5.1 on 2025-07-30 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_leveltwodepartments'),
    ]

    operations = [
        migrations.AddField(
            model_name='leveltwosection',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leveltwo_departments', to='app1.leveltwodepartments'),
            preserve_default=False,
        ),
    ]
