# Generated by Django 5.1 on 2025-07-30 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_leveltwosection_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillmatrix',
            old_name='uploaded_by',
            new_name='approved_by',
        ),
        migrations.RenameField(
            model_name='skillmatrix',
            old_name='updated_on',
            new_name='last_updated_on',
        ),
        migrations.RenameField(
            model_name='skillmatrix',
            old_name='next_review',
            new_name='next_updation_date',
        ),
        migrations.RemoveField(
            model_name='operationlist',
            name='section',
        ),
        migrations.RemoveField(
            model_name='skillmatrix',
            name='department',
        ),
        migrations.AddField(
            model_name='skillmatrix',
            name='Eff_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skillmatrix',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.leveltwodepartments'),
        ),
        migrations.AddField(
            model_name='skillmatrix',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='app1.leveltwosection'),
        ),
        migrations.AddField(
            model_name='skillmatrix',
            name='rev_no_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='app1.skillmatrix'),
        ),
        migrations.CreateModel(
            name='MonthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('plan', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_select', to='app1.leveltwodepartments')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_name', to='app1.operatormaster')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines_data', to='app1.leveltwosection')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='app1.operationlist')),
            ],
        ),
    ]
